//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 3.0 -InputFile running-person-dark-theme.json
//       
//       Input file:
//           running-person-dark-theme.json (22581 bytes created 17:06+02:00 Sep 19 2025)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   182 |
// |--------------------------+-------|
// | Expression animators     |     8 |
// | KeyFrame animators       |    20 |
// | Reference parameters     |     8 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     8 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     2 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |    12 |
// | CompositionSpriteShapes  |    14 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Name:        run forest run
    // Frame rate:  60 fps
    // Frame count: 34
    // Duration:    566.7 mS
    sealed class Running_person_dark_theme
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.567 seconds.
        internal const long c_durationTicks = 5666666;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new Running_person_dark_theme_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 34d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(5666666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 34d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Running_person_dark_theme_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 5666666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            AnimationController _animationController_1;
            AnimationController _animationController_2;
            AnimationController _animationController_3;
            AnimationController _animationController_4;
            AnimationController _animationController_5;
            AnimationController _animationController_6;
            AnimationController _animationController_7;
            CompositionColorBrush _colorBrush_White;
            CompositionContainerShape _containerShape_00;
            CompositionContainerShape _containerShape_01;
            CompositionContainerShape _containerShape_02;
            CompositionContainerShape _containerShape_03;
            CompositionContainerShape _containerShape_04;
            CompositionContainerShape _containerShape_05;
            CompositionContainerShape _containerShape_06;
            CompositionContainerShape _containerShape_07;
            CompositionContainerShape _containerShape_08;
            CompositionContainerShape _containerShape_09;
            CompositionContainerShape _containerShape_10;
            CompositionContainerShape _containerShape_11;
            CompositionPathGeometry _pathGeometry_1;
            CompositionPathGeometry _pathGeometry_2;
            CompositionPathGeometry _pathGeometry_4;
            CompositionPathGeometry _pathGeometry_5;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_00;
            CubicBezierEasingFunction _cubicBezierEasingFunction_01;
            CubicBezierEasingFunction _cubicBezierEasingFunction_02;
            CubicBezierEasingFunction _cubicBezierEasingFunction_03;
            CubicBezierEasingFunction _cubicBezierEasingFunction_04;
            CubicBezierEasingFunction _cubicBezierEasingFunction_05;
            CubicBezierEasingFunction _cubicBezierEasingFunction_06;
            CubicBezierEasingFunction _cubicBezierEasingFunction_07;
            CubicBezierEasingFunction _cubicBezierEasingFunction_08;
            CubicBezierEasingFunction _cubicBezierEasingFunction_09;
            CubicBezierEasingFunction _cubicBezierEasingFunction_10;
            CubicBezierEasingFunction _cubicBezierEasingFunction_11;
            CubicBezierEasingFunction _cubicBezierEasingFunction_12;
            CubicBezierEasingFunction _cubicBezierEasingFunction_13;
            CubicBezierEasingFunction _cubicBezierEasingFunction_14;
            CubicBezierEasingFunction _cubicBezierEasingFunction_15;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: so ayk Outlines
            // Transforms: so ayk uc Outlines
            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress*0.8292683+0.1707317", "_", _root);
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines
            AnimationController AnimationController_1()
            {
                if (_animationController_1 != null) { return _animationController_1; }
                var result = _animationController_1 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_1, "Progress", "_.Progress*0.9189189+0.08108108", "_", _root);
                return result;
            }

            AnimationController AnimationController_2()
            {
                if (_animationController_2 != null) { return _animationController_2; }
                var result = _animationController_2 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_2, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: so ayk Outlines 3
            // Transforms: so ayk uc Outlines 3
            AnimationController AnimationController_3()
            {
                if (_animationController_3 != null) { return _animationController_3; }
                var result = _animationController_3 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_3, "Progress", "_.Progress*0.7234042", "_", _root);
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines 3
            AnimationController AnimationController_4()
            {
                if (_animationController_4 != null) { return _animationController_4; }
                var result = _animationController_4 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_4, "Progress", "_.Progress*0.9189189", "_", _root);
                return result;
            }

            AnimationController AnimationController_5()
            {
                if (_animationController_5 != null) { return _animationController_5; }
                var result = _animationController_5 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_5, "Progress", "_.Progress*0.85", "_", _root);
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 2
            AnimationController AnimationController_6()
            {
                if (_animationController_6 != null) { return _animationController_6; }
                var result = _animationController_6 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_6, "Progress", "_.Progress*0.9444444+0.05555556", "_", _root);
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 3
            AnimationController AnimationController_7()
            {
                if (_animationController_7 != null) { return _animationController_7; }
                var result = _animationController_7 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_7, "Progress", "_.Progress*0.8947368", "_", _root);
                return result;
            }

            // - - - - PreComp layer: orj
            // - - - Layer aggregator
            // - - Transforms: kafa Outlines
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(31.5F, 0F));
                    builder.AddCubicBezier(new Vector2(31.5F, 17.3969994F), new Vector2(17.3959999F, 31.5F), new Vector2(0F, 31.5F));
                    builder.AddCubicBezier(new Vector2(-17.3959999F, 31.5F), new Vector2(-31.5F, 17.3969994F), new Vector2(-31.5F, 0F));
                    builder.AddCubicBezier(new Vector2(-31.5F, -17.3969994F), new Vector2(-17.3959999F, -31.5F), new Vector2(0F, -31.5F));
                    builder.AddCubicBezier(new Vector2(17.3959999F, -31.5F), new Vector2(31.5F, -17.3969994F), new Vector2(31.5F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-20.5270004F, 56.3959999F));
                    builder.AddCubicBezier(new Vector2(-28.4720001F, 53.5040016F), new Vector2(-32.605999F, 44.6380005F), new Vector2(-29.7150002F, 36.6940002F));
                    builder.AddLine(new Vector2(0.824999988F, -47.2099991F));
                    builder.AddCubicBezier(new Vector2(3.71600008F, -55.1549988F), new Vector2(12.5819998F, -59.2890015F), new Vector2(20.5270004F, -56.3969994F));
                    builder.AddCubicBezier(new Vector2(28.4720001F, -53.5050011F), new Vector2(32.605999F, -44.6399994F), new Vector2(29.7150002F, -36.6949997F));
                    builder.AddLine(new Vector2(-0.824000001F, 47.2099991F));
                    builder.AddCubicBezier(new Vector2(-3.71600008F, 55.1549988F), new Vector2(-12.5819998F, 59.2890015F), new Vector2(-20.5270004F, 56.3959999F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-50.0419998F, 28.8929996F));
                    builder.AddCubicBezier(new Vector2(-54.2700005F, 21.5709991F), new Vector2(-51.7369995F, 12.1210003F), new Vector2(-44.4160004F, 7.89300013F));
                    builder.AddLine(new Vector2(29.0440006F, -34.5180016F));
                    builder.AddCubicBezier(new Vector2(36.3660011F, -38.7459984F), new Vector2(45.8160019F, -36.2130013F), new Vector2(50.0439987F, -28.8910007F));
                    builder.AddCubicBezier(new Vector2(54.2709999F, -21.5699997F), new Vector2(51.7389984F, -12.1210003F), new Vector2(44.4169998F, -7.89300013F));
                    builder.AddLine(new Vector2(-29.0429993F, 34.5200005F));
                    builder.AddCubicBezier(new Vector2(-36.3650017F, 38.7470016F), new Vector2(-45.8149986F, 36.2150002F), new Vector2(-50.0419998F, 28.8929996F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - PreComp layer: orj
            // - - - Layer aggregator
            // - - ShapeGroup: Group 1 Offset:<393.463, 376.487>
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-21.8430004F, 60.0110016F));
                    builder.AddCubicBezier(new Vector2(-36.3740005F, 54.7220001F), new Vector2(-43.8660011F, 38.6549988F), new Vector2(-38.5779991F, 24.1229992F));
                    builder.AddLine(new Vector2(-14.0459995F, -43.2770004F));
                    builder.AddCubicBezier(new Vector2(-8.75699997F, -57.8089981F), new Vector2(7.31099987F, -65.3010025F), new Vector2(21.8419991F, -60.012001F));
                    builder.AddCubicBezier(new Vector2(36.3740005F, -54.7229996F), new Vector2(43.8660011F, -38.6559982F), new Vector2(38.5769997F, -24.1240005F));
                    builder.AddLine(new Vector2(14.0450001F, 43.276001F));
                    builder.AddCubicBezier(new Vector2(8.75599957F, 57.8069992F), new Vector2(-7.31099987F, 65.3000031F), new Vector2(-21.8430004F, 60.0110016F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(41.8930016F, 30.4179993F));
                    builder.AddCubicBezier(new Vector2(46.2560005F, 24.4090004F), new Vector2(44.9099998F, 15.9239998F), new Vector2(38.901001F, 11.5620003F));
                    builder.AddLine(new Vector2(-23.0380001F, -33.4099998F));
                    builder.AddCubicBezier(new Vector2(-29.0459995F, -37.7719994F), new Vector2(-37.5320015F, -36.4259987F), new Vector2(-41.894001F, -30.4169998F));
                    builder.AddCubicBezier(new Vector2(-46.2560005F, -24.4090004F), new Vector2(-44.9099998F, -15.9239998F), new Vector2(-38.901001F, -11.5609999F));
                    builder.AddLine(new Vector2(23.0380001F, 33.4099998F));
                    builder.AddCubicBezier(new Vector2(29.0450001F, 37.7719994F), new Vector2(37.5309982F, 36.4259987F), new Vector2(41.8930016F, 30.4179993F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-29.9699993F, 28.1630001F));
                    builder.AddCubicBezier(new Vector2(-24.8850002F, 33.5740013F), new Vector2(-16.2980003F, 33.8419991F), new Vector2(-10.8870001F, 28.757F));
                    builder.AddLine(new Vector2(29.3780003F, -9.08199978F));
                    builder.AddCubicBezier(new Vector2(34.7890015F, -14.1669998F), new Vector2(35.0550003F, -22.7530003F), new Vector2(29.9710007F, -28.1639996F));
                    builder.AddCubicBezier(new Vector2(24.8859997F, -33.5750008F), new Vector2(16.2999992F, -33.8419991F), new Vector2(10.8879995F, -28.7579994F));
                    builder.AddLine(new Vector2(-29.3770008F, 9.08100033F));
                    builder.AddCubicBezier(new Vector2(-34.7879982F, 14.1660004F), new Vector2(-35.0550003F, 22.7520008F), new Vector2(-29.9699993F, 28.1630001F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_White()
            {
                return (_colorBrush_White == null)
                    ? _colorBrush_White = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF))
                    : _colorBrush_White;
            }

            // - PreComp layer: orj
            // Layer aggregator
            // Transforms for so ayk Outlines
            CompositionContainerShape ContainerShape_00()
            {
                if (_containerShape_00 != null) { return _containerShape_00; }
                var result = _containerShape_00 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(365.75F, 412F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<351.939, 452.753>
                shapes.Add(SpriteShape_01());
                // Transforms: so ayk uc Outlines
                shapes.Add(ContainerShape_01());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines
            // Transforms for so ayk uc Outlines
            CompositionContainerShape ContainerShape_01()
            {
                if (_containerShape_01 != null) { return _containerShape_01; }
                var result = _containerShape_01 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(334.75F, 496.5F);
                // ShapeGroup: Group 1 Offset:<298.68, 517.211>
                result.Shapes.Add(SpriteShape_02());
                return result;
            }

            // - PreComp layer: orj
            // Layer aggregator
            // Layer: so ayk Outlines 3
            CompositionContainerShape ContainerShape_02()
            {
                if (_containerShape_02 != null) { return _containerShape_02; }
                var result = _containerShape_02 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(365.75F, 412F);
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<351.939, 452.753>
                shapes.Add(SpriteShape_03());
                // Transforms: so ayk uc Outlines 3
                shapes.Add(ContainerShape_03());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines 3
            // Transforms for so ayk uc Outlines 3
            CompositionContainerShape ContainerShape_03()
            {
                if (_containerShape_03 != null) { return _containerShape_03; }
                var result = _containerShape_03 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(334.75F, 496.5F);
                // ShapeGroup: Group 1 Offset:<298.68, 517.211>
                result.Shapes.Add(SpriteShape_04());
                return result;
            }

            // - PreComp layer: orj
            // Layer aggregator
            // Transforms for so ayk Outlines 2
            CompositionContainerShape ContainerShape_04()
            {
                if (_containerShape_04 != null) { return _containerShape_04; }
                var result = _containerShape_04 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(365.75F, 412F);
                result.Offset = new Vector2(-400F, -400F);
                // Offset:<416, 413>
                result.TransformMatrix = new Matrix3x2(1F, 0F, 0F, 1F, 416F, 413F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<351.939, 452.753>
                shapes.Add(SpriteShape_05());
                // Transforms: so ayk uc Outlines 2
                shapes.Add(ContainerShape_05());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Offset:<416, 413>
            // Transforms for so ayk uc Outlines 2
            CompositionContainerShape ContainerShape_05()
            {
                if (_containerShape_05 != null) { return _containerShape_05; }
                var result = _containerShape_05 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(334.75F, 496.5F);
                // ShapeGroup: Group 1 Offset:<298.68, 517.211>
                result.Shapes.Add(SpriteShape_06());
                return result;
            }

            // - PreComp layer: orj
            // Layer aggregator
            // Transforms for sa om Outlines
            CompositionContainerShape ContainerShape_06()
            {
                if (_containerShape_06 != null) { return _containerShape_06; }
                var result = _containerShape_06 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(416F, 331F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<445.413, 353.538>
                shapes.Add(SpriteShape_08());
                // Transforms: sa uc Outlines
                shapes.Add(ContainerShape_07());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Transforms: sa om Outlines
            // Transforms for sa uc Outlines
            CompositionContainerShape ContainerShape_07()
            {
                if (_containerShape_07 != null) { return _containerShape_07; }
                var result = _containerShape_07 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(477F, 375.75F);
                // ShapeGroup: Group 1 Offset:<496.339, 357.437>
                result.Shapes.Add(SpriteShape_09());
                return result;
            }

            // - PreComp layer: orj
            // Layer aggregator
            // Transforms for sa om Outlines 2
            CompositionContainerShape ContainerShape_08()
            {
                if (_containerShape_08 != null) { return _containerShape_08; }
                var result = _containerShape_08 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(416F, 331F);
                result.Offset = new Vector2(-402F, -396F);
                // Offset:<394, 398>
                result.TransformMatrix = new Matrix3x2(1F, 0F, 0F, 1F, 394F, 398F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<445.413, 353.538>
                shapes.Add(SpriteShape_10());
                // Transforms: sa uc Outlines 2
                shapes.Add(ContainerShape_09());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 2
            // Transforms for sa uc Outlines 2
            CompositionContainerShape ContainerShape_09()
            {
                if (_containerShape_09 != null) { return _containerShape_09; }
                var result = _containerShape_09 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(477F, 375.75F);
                // ShapeGroup: Group 1 Offset:<496.339, 357.437>
                result.Shapes.Add(SpriteShape_11());
                return result;
            }

            // - PreComp layer: orj
            // Layer aggregator
            // Layer: sa om Outlines 3
            CompositionContainerShape ContainerShape_10()
            {
                if (_containerShape_10 != null) { return _containerShape_10; }
                var result = _containerShape_10 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(416F, 331F);
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<445.413, 353.538>
                shapes.Add(SpriteShape_12());
                // Transforms: sa uc Outlines 3
                shapes.Add(ContainerShape_11());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 3
            // Transforms for sa uc Outlines 3
            CompositionContainerShape ContainerShape_11()
            {
                if (_containerShape_11 != null) { return _containerShape_11; }
                var result = _containerShape_11 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(477F, 375.75F);
                // ShapeGroup: Group 1 Offset:<496.339, 357.437>
                result.Shapes.Add(SpriteShape_13());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Transforms: kafa Outlines
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            CompositionPathGeometry PathGeometry_1()
            {
                return (_pathGeometry_1 == null)
                    ? _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()))
                    : _pathGeometry_1;
            }

            CompositionPathGeometry PathGeometry_2()
            {
                return (_pathGeometry_2 == null)
                    ? _pathGeometry_2 = _c.CreatePathGeometry(new CompositionPath(Geometry_2()))
                    : _pathGeometry_2;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // ShapeGroup: Group 1 Offset:<393.463, 376.487>
            CompositionPathGeometry PathGeometry_3()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
            }

            CompositionPathGeometry PathGeometry_4()
            {
                return (_pathGeometry_4 == null)
                    ? _pathGeometry_4 = _c.CreatePathGeometry(new CompositionPath(Geometry_4()))
                    : _pathGeometry_4;
            }

            CompositionPathGeometry PathGeometry_5()
            {
                return (_pathGeometry_5 == null)
                    ? _pathGeometry_5 = _c.CreatePathGeometry(new CompositionPath(Geometry_5()))
                    : _pathGeometry_5;
            }

            // - PreComp layer: orj
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                // Offset:<421.5, 282.5>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 421.5F, 282.5F), ColorBrush_White());;
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                // Offset:<351.939, 452.753>
                var geometry = PathGeometry_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 351.938995F, 452.752991F), ColorBrush_White());;
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: so ayk Outlines
            // Transforms: so ayk uc Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                // Offset:<298.68, 517.211>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 298.679993F, 517.210999F), ColorBrush_White());;
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines 3
            // Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                // Offset:<351.939, 452.753>
                var geometry = PathGeometry_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 351.938995F, 452.752991F), ColorBrush_White());;
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: so ayk Outlines 3
            // Transforms: so ayk uc Outlines 3
            // Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                // Offset:<298.68, 517.211>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 298.679993F, 517.210999F), ColorBrush_White());;
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Offset:<416, 413>
            // Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                // Offset:<351.939, 452.753>
                var geometry = PathGeometry_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 351.938995F, 452.752991F), ColorBrush_White());;
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // -  Offset:<416, 413>
            // Transforms: so ayk uc Outlines 2
            // Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                // Offset:<298.68, 517.211>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 298.679993F, 517.210999F), ColorBrush_White());;
                return result;
            }

            // - PreComp layer: orj
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                // Offset:<393.463, 376.487>
                var geometry = PathGeometry_3();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 393.463013F, 376.487F), ColorBrush_White());;
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Transforms: sa om Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                // Offset:<445.413, 353.538>
                var geometry = PathGeometry_4();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 445.412994F, 353.537994F), ColorBrush_White());;
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Transforms: sa om Outlines
            // Transforms: sa uc Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                // Offset:<496.339, 357.437>
                var geometry = PathGeometry_5();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 496.338989F, 357.437012F), ColorBrush_White());;
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 2
            // Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                // Offset:<445.413, 353.538>
                var geometry = PathGeometry_4();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 445.412994F, 353.537994F), ColorBrush_White());;
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: sa om Outlines 2
            // Transforms: sa uc Outlines 2
            // Path 1
            CompositionSpriteShape SpriteShape_11()
            {
                // Offset:<496.339, 357.437>
                var geometry = PathGeometry_5();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 496.338989F, 357.437012F), ColorBrush_White());;
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 3
            // Path 1
            CompositionSpriteShape SpriteShape_12()
            {
                // Offset:<445.413, 353.538>
                var geometry = PathGeometry_4();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 445.412994F, 353.537994F), ColorBrush_White());;
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: sa om Outlines 3
            // Transforms: sa uc Outlines 3
            // Path 1
            CompositionSpriteShape SpriteShape_13()
            {
                // Offset:<496.339, 357.437>
                var geometry = PathGeometry_5();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 496.338989F, 357.437012F), ColorBrush_White());;
                return result;
            }

            // Transforms for orj Scale(1,1,0)
            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(800F, 800F);
                // Scale:<1, 1>
                result.TransformMatrix = new Matrix4x4(1F, 0F, 0F, 0F, 0F, 1F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 1F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // PreComp layer: orj
                result.Children.InsertAtTop(ContainerVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_00()
            {
                return (_cubicBezierEasingFunction_00 == null)
                    ? _cubicBezierEasingFunction_00 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 0.493000001F))
                    : _cubicBezierEasingFunction_00;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_01()
            {
                return (_cubicBezierEasingFunction_01 == null)
                    ? _cubicBezierEasingFunction_01 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0.479999989F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_01;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_02()
            {
                return (_cubicBezierEasingFunction_02 == null)
                    ? _cubicBezierEasingFunction_02 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 0.537999988F))
                    : _cubicBezierEasingFunction_02;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_03()
            {
                return (_cubicBezierEasingFunction_03 == null)
                    ? _cubicBezierEasingFunction_03 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0.64200002F), new Vector2(0.666999996F, 0.922999978F))
                    : _cubicBezierEasingFunction_03;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_04()
            {
                return (_cubicBezierEasingFunction_04 == null)
                    ? _cubicBezierEasingFunction_04 = _c.CreateCubicBezierEasingFunction(new Vector2(0.818000019F, 0F), new Vector2(0.95599997F, 1F))
                    : _cubicBezierEasingFunction_04;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_05()
            {
                return (_cubicBezierEasingFunction_05 == null)
                    ? _cubicBezierEasingFunction_05 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0.879999995F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_05;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_06()
            {
                return (_cubicBezierEasingFunction_06 == null)
                    ? _cubicBezierEasingFunction_06 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_06;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_07()
            {
                return (_cubicBezierEasingFunction_07 == null)
                    ? _cubicBezierEasingFunction_07 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0.270000011F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_07;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_08()
            {
                return (_cubicBezierEasingFunction_08 == null)
                    ? _cubicBezierEasingFunction_08 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0.189999998F), new Vector2(0.666999996F, 0.746999979F))
                    : _cubicBezierEasingFunction_08;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_09()
            {
                return (_cubicBezierEasingFunction_09 == null)
                    ? _cubicBezierEasingFunction_09 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0.68599999F), new Vector2(0.615999997F, 1F))
                    : _cubicBezierEasingFunction_09;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_10()
            {
                return (_cubicBezierEasingFunction_10 == null)
                    ? _cubicBezierEasingFunction_10 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0.199000001F), new Vector2(0.666999996F, 0.869000018F))
                    : _cubicBezierEasingFunction_10;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_11()
            {
                return (_cubicBezierEasingFunction_11 == null)
                    ? _cubicBezierEasingFunction_11 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 0.90200001F))
                    : _cubicBezierEasingFunction_11;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_12()
            {
                return (_cubicBezierEasingFunction_12 == null)
                    ? _cubicBezierEasingFunction_12 = _c.CreateCubicBezierEasingFunction(new Vector2(0.377999991F, 0.0520000011F), new Vector2(0.611000001F, 1F))
                    : _cubicBezierEasingFunction_12;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_13()
            {
                return (_cubicBezierEasingFunction_13 == null)
                    ? _cubicBezierEasingFunction_13 = _c.CreateCubicBezierEasingFunction(new Vector2(0.270999998F, 0.00300000003F), new Vector2(0.591000021F, 1F))
                    : _cubicBezierEasingFunction_13;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_14()
            {
                return (_cubicBezierEasingFunction_14 == null)
                    ? _cubicBezierEasingFunction_14 = _c.CreateCubicBezierEasingFunction(new Vector2(0.351000011F, 0F), new Vector2(0.356999993F, 1F))
                    : _cubicBezierEasingFunction_14;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_15()
            {
                return (_cubicBezierEasingFunction_15 == null)
                    ? _cubicBezierEasingFunction_15 = _c.CreateCubicBezierEasingFunction(new Vector2(0.545000017F, 0F), new Vector2(0.518000007F, 1F))
                    : _cubicBezierEasingFunction_15;
            }

            // PreComp layer: orj
            InsetClip InsetClip_0()
            {
                var result = _c.CreateInsetClip();
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Transforms: sa om Outlines
            // Transforms: sa uc Outlines
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 5.95.
                result.InsertKeyFrame(0.174999997F, -21.4239998F, CubicBezierEasingFunction_09());
                // Frame 13.6.
                result.InsertKeyFrame(0.400000006F, 21.2040005F, CubicBezierEasingFunction_10());
                // Frame 18.7.
                result.InsertKeyFrame(0.550000012F, 13F, CubicBezierEasingFunction_11());
                // Frame 25.5.
                result.InsertKeyFrame(0.75F, -10.1899996F, CubicBezierEasingFunction_12());
                // Frame 34.
                result.InsertKeyFrame(1F, 0F, CubicBezierEasingFunction_13());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Transforms: sa om Outlines
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.5F, 146F, CubicBezierEasingFunction_14());
                // Frame 34.
                result.InsertKeyFrame(1F, 0F, CubicBezierEasingFunction_15());
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: sa om Outlines 3
            // Transforms: sa uc Outlines 3
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_21p204()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.529411793F, 0F, HoldThenStepEasingFunction());
                // Frame 25.
                result.InsertKeyFrame(0.735294104F, -21.4239998F, CubicBezierEasingFunction_09());
                // Frame 34.
                result.InsertKeyFrame(1F, 21.2040005F, CubicBezierEasingFunction_10());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 3
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_146()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 16.11.
                result.InsertKeyFrame(0.473684222F, 0F, HoldThenStepEasingFunction());
                // Frame 34.
                result.InsertKeyFrame(1F, 146F, CubicBezierEasingFunction_14());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_6_to_m107()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 6F, CubicBezierEasingFunction_03());
                // Frame 11.03.
                result.InsertKeyFrame(0.32432431F, -85F, CubicBezierEasingFunction_04());
                // Frame 18.38.
                result.InsertKeyFrame(0.540540516F, -107F, CubicBezierEasingFunction_05());
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: so ayk Outlines
            // Transforms: so ayk uc Outlines
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_9_to_47()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 9F, CubicBezierEasingFunction_00());
                // Frame 11.61.
                result.InsertKeyFrame(0.341463417F, 94F, CubicBezierEasingFunction_01());
                // Frame 19.9.
                result.InsertKeyFrame(0.585365832F, 47F, CubicBezierEasingFunction_02());
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: sa om Outlines 2
            // Transforms: sa uc Outlines 2
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_13_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 13F, CubicBezierEasingFunction_11());
                // Frame 8.
                result.InsertKeyFrame(0.235294119F, -10.1899996F, CubicBezierEasingFunction_12());
                // Frame 18.
                result.InsertKeyFrame(0.529411793F, 0F, CubicBezierEasingFunction_13());
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // -  Offset:<416, 413>
            // Transforms: so ayk uc Outlines 2
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_47_to_47()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 47F, HoldThenStepEasingFunction());
                // Frame 6.8.
                result.InsertKeyFrame(0.200000003F, -37F, CubicBezierEasingFunction_07());
                // Frame 13.6.
                result.InsertKeyFrame(0.400000006F, 9F, CubicBezierEasingFunction_00());
                // Frame 25.5.
                result.InsertKeyFrame(0.75F, 94F, CubicBezierEasingFunction_01());
                // Frame 34.
                result.InsertKeyFrame(1F, 47F, CubicBezierEasingFunction_02());
                return result;
            }

            // - - - PreComp layer: orj
            // - - Layer aggregator
            // - Layer: so ayk Outlines 3
            // Transforms: so ayk uc Outlines 3
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_47_to_94()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 47F, StepThenHoldEasingFunction());
                // Frame 12.3.
                result.InsertKeyFrame(0.361702114F, 47F, HoldThenStepEasingFunction());
                // Frame 18.09.
                result.InsertKeyFrame(0.53191489F, -37F, CubicBezierEasingFunction_07());
                // Frame 23.87.
                result.InsertKeyFrame(0.702127635F, 9F, CubicBezierEasingFunction_00());
                // Frame 34.
                result.InsertKeyFrame(1F, 94F, CubicBezierEasingFunction_01());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 2
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_146_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 146F, CubicBezierEasingFunction_14());
                // Frame 18.89.
                result.InsertKeyFrame(0.555555582F, 0F, CubicBezierEasingFunction_15());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines 3
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_m107_to_6()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, -107F, StepThenHoldEasingFunction());
                // Frame 15.62.
                result.InsertKeyFrame(0.459459454F, -107F, HoldThenStepEasingFunction());
                // Frame 24.81.
                result.InsertKeyFrame(0.729729712F, -26F, CubicBezierEasingFunction_08());
                // Frame 34.
                result.InsertKeyFrame(1F, 6F, CubicBezierEasingFunction_03());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Offset:<416, 413>
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_m107_to_m107()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, -107F, HoldThenStepEasingFunction());
                // Frame 8.5.
                result.InsertKeyFrame(0.25F, -26F, CubicBezierEasingFunction_08());
                // Frame 17.
                result.InsertKeyFrame(0.5F, 6F, CubicBezierEasingFunction_03());
                // Frame 27.2.
                result.InsertKeyFrame(0.800000012F, -85F, CubicBezierEasingFunction_04());
                // Frame 34.
                result.InsertKeyFrame(1F, -107F, CubicBezierEasingFunction_05());
                return result;
            }

            // PreComp layer: orj
            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(800F, 800F);
                var shapes = result.Shapes;
                // Transforms: kafa Outlines
                shapes.Add(SpriteShape_00());
                // Layer: so ayk Outlines
                shapes.Add(ContainerShape_00());
                // Layer: so ayk Outlines 3
                shapes.Add(ContainerShape_02());
                // Offset:<416, 413>
                shapes.Add(ContainerShape_04());
                // ShapeGroup: Group 1 Offset:<393.463, 376.487>
                shapes.Add(SpriteShape_07());
                // Transforms: sa om Outlines
                shapes.Add(ContainerShape_06());
                // Layer: sa om Outlines 2
                shapes.Add(ContainerShape_08());
                // Layer: sa om Outlines 3
                shapes.Add(ContainerShape_10());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 2.
                result.InsertKeyFrame(0.0588235296F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 9.
                result.InsertKeyFrame(0.264705896F, new Vector2(4F, 2F), CubicBezierEasingFunction_06());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines 3
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(4F, 2F), StepThenHoldEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.5F, new Vector2(4F, 2F), HoldThenStepEasingFunction());
                // Frame 29.
                result.InsertKeyFrame(0.852941155F, new Vector2(0F, 0F), CubicBezierEasingFunction_06());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Transforms: sa om Outlines
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.0882352963F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.294117659F, new Vector2(-2F, 4F), CubicBezierEasingFunction_06());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 3
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(-6F, -2F), StepThenHoldEasingFunction());
                // Frame 21.
                result.InsertKeyFrame(0.617647052F, new Vector2(-6F, -2F), HoldThenStepEasingFunction());
                // Frame 28.
                result.InsertKeyFrame(0.823529422F, new Vector2(-8F, 2F), CubicBezierEasingFunction_06());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: so ayk Outlines 3
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.5F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 2
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.529411793F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                return result;
            }

            // - - PreComp layer: orj
            // - Layer aggregator
            // Layer: sa om Outlines 3
            Vector2KeyFrameAnimation ShapeVisibilityAnimation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 18.
                result.InsertKeyFrame(0.529411793F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                return result;
            }

            internal Running_person_dark_theme_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(800F, 800F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape_00.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_6_to_m107(), AnimationController_1());
                _containerShape_00.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_2());
                _containerShape_00.StartAnimation("Scale", ShapeVisibilityAnimation_0(), AnimationController_2());
                _containerShape_01.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_9_to_47(), AnimationController_0());
                _containerShape_02.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m107_to_6(), AnimationController_4());
                _containerShape_02.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_2());
                _containerShape_02.StartAnimation("Scale", ShapeVisibilityAnimation_1(), AnimationController_2());
                _containerShape_03.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_47_to_94(), AnimationController_3());
                _containerShape_04.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m107_to_m107(), AnimationController_5());
                _containerShape_05.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_47_to_47(), AnimationController_5());
                _containerShape_06.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_1(), AnimationController_5());
                _containerShape_06.StartAnimation("Offset", OffsetVector2Animation_2(), AnimationController_2());
                _containerShape_07.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_0(), AnimationController_5());
                _containerShape_08.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_146_to_0(), AnimationController_6());
                _containerShape_08.StartAnimation("Scale", ShapeVisibilityAnimation_2(), AnimationController_2());
                _containerShape_09.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_13_to_0(), AnimationController_2());
                _containerShape_10.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_146(), AnimationController_7());
                _containerShape_10.StartAnimation("Offset", OffsetVector2Animation_3(), AnimationController_2());
                _containerShape_10.StartAnimation("Scale", ShapeVisibilityAnimation_3(), AnimationController_2());
                _containerShape_11.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_21p204(), AnimationController_2());
            }

            public void DestroyAnimations()
            {
                _containerShape_00.StopAnimation("RotationAngleInDegrees");
                _containerShape_00.StopAnimation("Offset");
                _containerShape_00.StopAnimation("Scale");
                _containerShape_01.StopAnimation("RotationAngleInDegrees");
                _containerShape_02.StopAnimation("RotationAngleInDegrees");
                _containerShape_02.StopAnimation("Offset");
                _containerShape_02.StopAnimation("Scale");
                _containerShape_03.StopAnimation("RotationAngleInDegrees");
                _containerShape_04.StopAnimation("RotationAngleInDegrees");
                _containerShape_05.StopAnimation("RotationAngleInDegrees");
                _containerShape_06.StopAnimation("RotationAngleInDegrees");
                _containerShape_06.StopAnimation("Offset");
                _containerShape_07.StopAnimation("RotationAngleInDegrees");
                _containerShape_08.StopAnimation("RotationAngleInDegrees");
                _containerShape_08.StopAnimation("Scale");
                _containerShape_09.StopAnimation("RotationAngleInDegrees");
                _containerShape_10.StopAnimation("RotationAngleInDegrees");
                _containerShape_10.StopAnimation("Offset");
                _containerShape_10.StopAnimation("Scale");
                _containerShape_11.StopAnimation("RotationAngleInDegrees");
            }

        }
    }
}
